### PR TITLE
Review frontend

### PR DESCRIPTION
**Pull request by cdreamer1**
- fixed typecheck and lint errors
- revise cog-modules code for mobile responsiveness

### CODE REVIEW

**Comment by cdreamer1** [comment]
@Tunki1201 
I would like you to review my code and merge it.

**Comment by Tunki1201** [comment]
please share review link

**Comment by cdreamer1** [comment]
This is my PR.
https://github.com/commune-ai/frontend/pull/96

**Comment by cdreamer1** [comment]
@Tunki1201 
Thanks.

**Comment by Tunki1201** [comment]
Great works.
Awesome.
Got it, thanks!
👍

**Pull request merged**
